function A(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("A"));}
function B(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("B"));}
function C(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("C"));}
function D(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("D"));}
function E(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("E"));}
function F(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("F"));}
function G(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("G"));}
function H(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("H"));}
function I(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("I"));}
function J(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("J"));}
function K(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("K"));}
function L(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("L"));}
function M(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("M"));}
function N(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("N"));}
function O(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("O"));}
function P(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("P"));}
function Q(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("Q"));}
function R(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("R"));}
function S(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("S"));}
function T(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("T"));}
function U(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("U"));}
function V(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("V"));}
function W(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("W"));}
function X(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("X"));}
function Y(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("Y"));}
function Z(){window.speechSynthesis.speak(new SpeechSynthesisUtterance("Z"));}
